// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicEbFLRoXaRINN02qyW2AF6BOYs-zbTQ',
    appId: '1:469211121859:web:94a2549473cf0a844ffa76',
    messagingSenderId: '469211121859',
    projectId: 'fruit-hub-7ba87',
    authDomain: 'fruit-hub-7ba87.firebaseapp.com',
    storageBucket: 'fruit-hub-7ba87.firebasestorage.app',
    measurementId: 'G-QTT0K6PHBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FEG0zyocKQ6uWOZXYUZ2NNOMec4Dekg',
    appId: '1:469211121859:android:eefbc7a5238c8a7f4ffa76',
    messagingSenderId: '469211121859',
    projectId: 'fruit-hub-7ba87',
    storageBucket: 'fruit-hub-7ba87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRYjO7HkK4Xd-0MVRtjos19gfjLDEPdU',
    appId: '1:469211121859:ios:83d804baeac8bbfd4ffa76',
    messagingSenderId: '469211121859',
    projectId: 'fruit-hub-7ba87',
    storageBucket: 'fruit-hub-7ba87.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRYjO7HkK4Xd-0MVRtjos19gfjLDEPdU',
    appId: '1:469211121859:ios:83d804baeac8bbfd4ffa76',
    messagingSenderId: '469211121859',
    projectId: 'fruit-hub-7ba87',
    storageBucket: 'fruit-hub-7ba87.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAicEbFLRoXaRINN02qyW2AF6BOYs-zbTQ',
    appId: '1:469211121859:web:00bac9b358e0cb344ffa76',
    messagingSenderId: '469211121859',
    projectId: 'fruit-hub-7ba87',
    authDomain: 'fruit-hub-7ba87.firebaseapp.com',
    storageBucket: 'fruit-hub-7ba87.firebasestorage.app',
    measurementId: 'G-FX9FCZ0J4D',
  );
}
